### ISSUE TITLE
Style issues after enabling module

### ISSUE THREAD

**Issue by meinemitternacht** [Imatic-IT/imatic-mantis-formatting#2]
I understand this is not an officially supported module, so there are bound to be a few problems.  There is a minor styling issue that I hope can be fixed easily.

Some elements seem to always break to the next line in places where they used to be inline.  The `trash` icon when removing a relationship from an issue was inline before, and the issue status icon, issue ID, category, and description for each issue on the `Roadmap` page were all on the same line.

**Relationships Block**
![Screenshot_20201221_123014](https://user-images.githubusercontent.com/2513299/102805181-d601fd80-4388-11eb-81bb-2f9ee33ebd9d.png)

**Roadmap Page**
![Screenshot_20201221_123400](https://user-images.githubusercontent.com/2513299/102805184-d69a9400-4388-11eb-9aff-d018a3a3cdb2.png)

**Comment by janpekar** [comment]
Thank you for the feedback. You are right with the unusual element "break". 
We will fix it, but before January due to a developer's vacation.

**Comment by meinemitternacht** [comment]
@janpekar Thank you! No rush, it is purely a style issue and is not bothering anyone.

**Comment by nenadalm** [comment]
Thanks. All issues with line breaks should be fixed now in 0.0.5.

There is multiline flag in formatting hook, but I thought it was used either incorrectly or not used at all due to me assuming different operator priority when printing the flag, so that flag is now taken into account which fixes all mentioned issues by not wrapping one line line strings in `<p>`.

**Comment by meinemitternacht** [comment]
@nenadalm Confirmed, everything works as expected now.  Thank you.
